import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
// import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
          <body>
          <header className="fixed top-0 right-0 z-150 flex justify-end items-center p-3 sm:p-4 gap-2 sm:gap-4 h-14 sm:h-16 bg-white/90 backdrop-blur-sm border-b border-gray-200/50">
            <SignedOut>
              <SignInButton>
                <button className="text-gray-700 hover:text-black rounded-full font-medium text-base h-11 sm:h-12 px-4 sm:px-5 cursor-pointer transition-colors min-w-[80px] active:scale-95"> 
                  Sign In
                </button>
              </SignInButton>
              <SignUpButton>
                <button className="bg-[#499eff] hover:bg-[#3a8ae6] text-white rounded-full font-medium text-base h-11 sm:h-12 px-4 sm:px-5 cursor-pointer transition-all min-w-[80px] active:scale-95">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}